source 'http://rubygems.vmcommerce.intra/'


gem 'cucumber'
gem 'hash_compare'
gem 'hash_diff'
gem 'httparty'
gem 'json'
gem 'mime-types', '~> 1.16'
gem 'net-ssh'
gem 'pry'
gem 'pry-byebug'
gem 'rspec', require: 'spec'
gem 'ruby-oci8', '~> 2.2', '>= 2.2.3'
gem 'faker'
gem 'cpf_faker'
gem 'savon', '~> 2'
gem 'bunny'
gem 'json-schema'
