local:
  habbit:
    vhost: '/username-qa'
    port: '5672'
    username: 'user'
    password: 'pass'

  valid:
    username: username
    password: username123

  invalid_username:
    username: lockabc
    password: username123

  empty_username:
    username:
    password: username123

  invalid_password:
    username: username
    password: usernameabc

  empty_password:
    username: username
    password:

qa:
  token_cte:
    username: username
    password: username
    grant_type: password
    client_secret: f0357cca-60a4-4d40-9578-d8573dfeb351
    client_id: username-test

  habbit:
    vhost: '/username-qa'
    port: '5672'
    username: 'user'
    password: 'pass'

  valid:
    username: username
    password: username123

  invalid_username:
    username: username
    password: username123

  empty_username:
    username:
    password: username123

  invalid_password:
    username: username
    password: usernameabc

  empty_password:
    username: username
    password:

stg:
  token_cte:
    username: username
    password: username
    grant_type: password
    client_secret: 95ec0df0-2fde-4cdc-a832-c8f79f0c87fe
    client_id: username-test

  habbit:
    vhost: '/username'
    port: '15672'
    username: 'user'
    password: 'pass'

  valid:
    username: username
    password: username123

  invalid_username:
    username: lockabc
    password: username123

  empty_username:
    username:
    password: username123

  invalid_password:
    username: username
    password: usernameabc

  empty_password:
    username: username
    password:
