local:
  adapter: oracle
  database: http://localhost:
  username: swmart
  password: swmart
  encoding: utf8

qa:
  adapter: oracle
  database: http://localhost
  username: swmart
  password: swmart
  encoding: utf8

stg:
  adapter: oracle
  database: http://localhost
  username: lockdown_usr
  password: lockdown_usr
  encoding: utf8
