local:
  server: 'http://localhost:8080'
  rabbitmq: 'http://localhost:8080'

qa:
  server: 'http://localhost:8080'

  token: 'http://localhost:8080'

stg:
  server: 'https://vip-aldebaran-olimpo.stg.vmcommerce.intra'
  rabbitmq: 'http://localhost:8080'
  token: 'http://localhost:8080'
